//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioAssist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhysioAssist.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As.
        /// </summary>
        internal static string Application_Coimmand_SavaAs {
            get {
                return ResourceManager.GetString("Application_Coimmand_SavaAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        internal static string Application_Command_About {
            get {
                return ResourceManager.GetString("Application_Command_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        internal static string Application_Command_Exit {
            get {
                return ResourceManager.GetString("Application_Command_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        internal static string Application_Command_New {
            get {
                return ResourceManager.GetString("Application_Command_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _Page.
        /// </summary>
        internal static string Application_Command_NewPage {
            get {
                return ResourceManager.GetString("Application_Command_NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next Page.
        /// </summary>
        internal static string Application_Command_NextPage {
            get {
                return ResourceManager.GetString("Application_Command_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        internal static string Application_Command_Open {
            get {
                return ResourceManager.GetString("Application_Command_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Prev Page.
        /// </summary>
        internal static string Application_Command_PrevPage {
            get {
                return ResourceManager.GetString("Application_Command_PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_rint.
        /// </summary>
        internal static string Application_Command_Print {
            get {
                return ResourceManager.GetString("Application_Command_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Previe_w.
        /// </summary>
        internal static string Application_Command_PrintPreview {
            get {
                return ResourceManager.GetString("Application_Command_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove Page.
        /// </summary>
        internal static string Application_Command_RemovePage {
            get {
                return ResourceManager.GetString("Application_Command_RemovePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string Application_Command_Save {
            get {
                return ResourceManager.GetString("Application_Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Background _Image.
        /// </summary>
        internal static string Application_Command_SetImage {
            get {
                return ResourceManager.GetString("Application_Command_SetImage", resourceCulture);
            }
        }
    }
}
